### ISSUE TITLE
UI Container import ERROR

### ISSUE THREAD

**Issue by minziran** [medianetlab/katana-slice_manager#58]
I used the command ./start.sh -g -m

Errors as following:

Traceback (most recent call last):
  File "/usr/local/bin/ui", line 11, in <module>
    load_entry_point('UI-CLI', 'console_scripts', 'ui')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1094, in resolve_comm                                         and
    cmd = self.get_command(ctx, cmd_name)
  File "/app/cli/cli.py", line 41, in get_command
    eval(code, ns, ns)
  File "/app/cli/commands/cmd_db.py", line 3, in <module>
    from sqlalchemy_utils import database_exists, create_database
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/__init__.py", line 1, in                                          <module>
    from .aggregates import aggregated  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/aggregates.py", line 372,                                          in <module>
    from .functions.orm import get_column_key
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/functions/__init__.py", l                                         ine 1, in <module>
    from .database import (  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/functions/database.py", l                                         ine 13, in <module>
    from ..expressions import explain_analyze
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/expressions.py", line 4,                                          in <module>
    from sqlalchemy.sql.expression import (
ImportError: cannot import name '_literal_as_text' from 'sqlalchemy.sql.expression' (/usr                                         /local/lib/python3.7/site-packages/sqlalchemy/sql/expression.py)
Traceback (most recent call last):
  File "/usr/local/bin/ui", line 11, in <module>
    load_entry_point('UI-CLI', 'console_scripts', 'ui')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1094, in resolve_comm                                         and
    cmd = self.get_command(ctx, cmd_name)
  File "/app/cli/cli.py", line 41, in get_command
    eval(code, ns, ns)
  File "/app/cli/commands/cmd_db.py", line 3, in <module>
    from sqlalchemy_utils import database_exists, create_database
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/__init__.py", line 1, in                                          <module>
    from .aggregates import aggregated  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/aggregates.py", line 372,                                          in <module>
    from .functions.orm import get_column_key
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/functions/__init__.py", l                                         ine 1, in <module>
    from .database import (  # noqa
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/functions/database.py", l                                         ine 13, in <module>
    from ..expressions import explain_analyze
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_utils/expressions.py", line 4,                                          in <module>
    from sqlalchemy.sql.expression import (
ImportError: cannot import name '_literal_as_text' from 'sqlalchemy.sql.expression' (/usr                                         /local/lib/python3.7/site-packages/sqlalchemy/sql/expression.py)

Thank you in advance!

**Comment by themisAnagno** [comment]
Hello @minziran, the current UI container is removed from the Katana software stack. In the future, we will implement another Web UI for interacting with the Slice Manager.
For the moment you can use the [swagger](https://github.com/medianetlab/katana-slice_manager/wiki/swagger), the [CLI tool](https://github.com/medianetlab/katana-slice_manager/wiki/cli), and/or directly the [NBI endpoints](https://github.com/medianetlab/katana-slice_manager/wiki/nbi)
